trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Actualizar paquetes e instalar Nginx'
  inputs:
    targetType: 'inline'
    script: |
      # Actualizar paquetes
      sudo apt-get update
      # Instalar Nginx
      sudo apt-get install -y nginx
      # Iniciar el servicio Nginx
      sudo systemctl start nginx
      # Habilitar Nginx para que se inicie en el arranque
      sudo systemctl enable nginx

- task: Bash@3
  displayName: 'Verificar estado del servicio Nginx'
  inputs:
    targetType: 'inline'
    script: |
      # Comprobar el estado de Nginx
      systemctl is-active --quiet nginx
      if [ $? -eq 0 ]; then
        echo "Nginx está funcionando correctamente."
      else
        echo "Error: Nginx no está funcionando."
        exit 1
      fi

