name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ caramelos1 }}" | docker login -u "${{oahp }}" --password-stdin

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t oahp/oahp:latest .

    - name: Push Docker image to DockerHub
      run: docker push oahp/oahp:latest

    - name: Run Docker container
      run: docker run -d --name my_container oahp/oahp:latest
