name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Chequear en que directorio estamos
      run: pwd && ls -l
      
    - name: Build Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -f /home/runner/work/pipeline/pipeline/nginx -t oahp .

    - name: Push Docker image to DockerHub
      run: docker push oahp/oahp

    - name: Run Docker container
      run: docker run -d --name my_container oahp/oahp

  
